# copyright CEA-LIST/DIASI/SIALV/LVA (2022)
# author CEA-LIST/DIASI/SIALV/LVA <julien.denize@cea.fr>
# license CeCILL version 2.1

_target_: 'sce.evaluation.LinearClassifierEvaluation'
_recursive_: False
trunk: ???
classifier: ???
optimizer: ???
pretrained_trunk_path: ???
