# copyright CEA-LIST/DIASI/SIALV/LVA (2022)
# author CEA-LIST/DIASI/SIALV/LVA <julien.denize@cea.fr>
# license CeCILL version 2.1

_target_: sce.transforms.LinearClassifierValTransform
_recursive_: True
resize: null
center_crop:
  _target_: sce.transforms.CenterCrop
  size: 32
to_tensor:
  _target_: sce.transforms.ToTensor
normalize:
  _target_: sce.transforms.Normalize
  dataset: cifar10
