# copyright CEA-LIST/DIASI/SIALV/LVA (2022)
# author CEA-LIST/DIASI/SIALV/LVA <julien.denize@cea.fr>
# license CeCILL version 2.1

_target_: sce.callbacks.ModelCheckpoint
dirpath: checkpoints/
filename: null
monitor: null
verbose: False
save_last: null
save_top_k: 1
save_weights_only: False
mode: min
auto_insert_metric_name: True
every_n_train_steps: null
train_time_interval: null
every_n_epochs: null
save_on_train_epoch_end: null
every_n_val_epochs: null
