# copyright CEA-LIST/DIASI/SIALV/LVA (2022)
# author CEA-LIST/DIASI/SIALV/LVA <julien.denize@cea.fr>
# license CeCILL version 2.1

_target_: sce.models.heads.MLPHead
activation_inplace: True
activation_layer: relu
affine: True
bias: True
dropout: 0.
dropout_inplace: True
hidden_dims: [1024]
input_dim: 1024
norm_layer: null
num_layers: 2
last_bias: True
last_norm: False
last_affine: False
output_dim: 128
