# copyright CEA-LIST/DIASI/SIALV/LVA (2022)
# author CEA-LIST/DIASI/SIALV/LVA <julien.denize@cea.fr>
# license CeCILL version 2.1

_target_: sce.optimizers.optimizer_factory
_recursive_: False
exclude_wd_norm: False
exclude_wd_bias: False
name: sgd
params:
  momentum: 0.9
  dampening: 0
  nesterov: False
  weight_decay: 0.
batch_size: null
initial_lr: 0.06
scaler: null
scheduler: null
