# copyright CEA-LIST/DIASI/SIALV/LVA (2022)
# author CEA-LIST/DIASI/SIALV/LVA <julien.denize@cea.fr>
# license CeCILL version 2.1

_target_: sce.schedulers.scheduler_factory
name: multi_step_lr
params:
  milestones: ???
  gamma: 0.1
  last_epoch: -1
  verbose: False
interval: epoch
