# copyright CEA-LIST/DIASI/SIALV/LVA (2022)
# author CEA-LIST/DIASI/SIALV/LVA <julien.denize@cea.fr>
# license CeCILL version 2.1

_target_: sce.datamodule.CIFAR100DataModule
_recursive_: False
datadir: 'data/'
train: null
val: null
test: null
